=== Smithsonian/dpo-cook/server/schemas/recipe.schema.json
{
    "$id": "https://schemas.3d.si.edu/cook/recipe.json",
    "$schema": "http://json-schema.org/draft-07/schema#",

    "title": "Smithsonian 3D Processing Recipe",

    "definitions": {
        "primitiveValue": {
            "$id": "#primitiveValue",
            "oneOf": [
                {
                    "type": "number"
                },
                {
                    "type": "boolean"
                },
                {
                    "type": "string"
                }
            ]
        },
        "taskParameter": {
            "$id": "#taskParameter",
            "oneOf": [
                {
                    "$ref": "#primitiveValue"
                },
                {
                    "type": "array",
                    "items": {
                        "$ref": "#primitiveValue"
                    }
                },
                {
                    "type": "object",
                    "items": {
                        "$ref": "#primitiveValue"
                    }

                }
            ]
        },
        "recipeParameterMetaSchema": {
            "$id": "#recipeParameterMetaSchema",
            "type": "object",
            "properties": {
                "type": {
                    "type": "string",
                    "const": "object"
                },
                "properties": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "object",
                        "oneOf": [
                            {
                                "properties": {
                                    "type": {
                                        "type": "string",
                                        "const": "number"
                                    },
                                    "minimum": {
                                        "type": "number"
                                    },
                                    "maximum": {
                                        "type": "number"
                                    },
                                    "multipleOf": {
                                        "type": "integer"
                                    },
                                    "default": {
                                        "type": "number"
                                    }
                                },
                                "required": [
                                    "type"
                                ]
                            },
                            {
                                "properties": {
                                    "type": {
                                        "type": "string",
                                        "const": "integer"
                                    },
                                    "minimum": {
                                        "type": "integer"
                                    },
                                    "maximum": {
                                        "type": "integer"
                                    },
                                    "multipleOf": {
                                        "type": "integer"
                                    },
                                    "default": {
                                        "type": "integer"
                                    }
                                },
                                "required": [
                                    "type"
                                ]
                            },
                            {
                                "properties": {
                                    "type": {
                                        "type": "string",
                                        "const": "boolean"
                                    },
                                    "default": {
                                        "type": "boolean"
                                    }
                                },
                                "required": [
                                    "type"
                                ]
                            },
                            {
                                "properties": {
                                    "type": {
                                        "type": "string",
                                        "const": "string"
                                    },
                                    "minLength": {
                                        "type": "integer"
                                    },
                                    "maxLength": {
                                        "type": "integer"
                                    },
                                    "default": {
                                        "type": "string"
                                    }
                                },
                                "required": [
                                    "type"
                                ]
                            }
                        ]
                    }
                },
                "required": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "additionalProperties": {
                    "type": "boolean",
                    "const": false
                }
            },
            "required": [
                "type",
                "properties",
                "additionalProperties"
            ]
        },
        "recipeStep": {
            "$id": "#recipeStep",
            "type": "object",
            "properties": {
                "task": {
                    "description": "name of the task to be executed in this step",
                    "type": "string",
                    "minLength": 1
                },
                "description": {
                    "description": "descriptive text for this recipe step",
                    "type": "string",
                    "minLength": 1
                },
                "parameters": {
                    "title": "task parameters",
                    "description": "primitive value or JSONata expression; strings must be put in quotes",
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#taskParameter"
                    }
                },
                "pre": {
                    "title": "variables defined before task is started",
                    "description": "primitive value or JSONata expression; strings must be put in quotes",
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#taskParameter"
                    }
                },
                "post": {
                    "title": "variables defined after task is done",
                    "description": "primitive value or JSONata expression; strings must be put in quotes",
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#taskParameter"
                    }
                },
                "success": {
                    "title": "name of next step to be executed in case of success",
                    "description": "name as string or JSONata expression; string must be put in quotes",
                    "type": "string",
                    "minLength": 1
                },
                "failure": {
                    "title": "name of next step to be executed in case of failure",
                    "description": "name as string or JSONata expression; string must be put in quotes",
                    "type": "string",
                    "minLength": 1
                }
            },
            "required": [
                "task",
                "parameters",
                "success",
                "failure"
            ],
            "additionalProperties": false
        }
    },

    "type": "object",
    "properties": {
        "id": {
            "description": "unique identifier for the recipe",
            "type": "string",
            "minLength": 1
        },
        "name": {
            "description": "recipe name",
            "type": "string",
            "minLength": 1
        },
        "description": {
            "description": "recipe description",
            "type": "string",
            "minLength": 1
        },
        "version": {
            "description": "version of the recipe, must be incremented each time recipe changes",
            "type": "string",
            "minLength": 1
        },
        "parameterSchema": {
            "description": "JSON schema for the recipe's parameters; the schema must be valid against this meta schema",
            "$ref": "#recipeParameterMetaSchema"
        },
        "start": {
            "description": "name of first step to be executed",
            "type": "string",
            "minLength": 1
        },
        "steps": {
            "description": "each recipe step consists of a task to be executed, and next steps in case of success or failure",
            "type": "object",
            "additionalProperties": {
                "$ref": "#recipeStep"
            }
        }
    },
    "required": [
        "id",
        "name",
        "version",
        "parameterSchema",
        "start",
        "steps"
    ],
    "additionalProperties": false
}

=== Smithsonian/dpo-cook/server/recipes/inspect-mesh.json
{
    "id": "ee77ee05-d832-4729-9914-18a96939f205",
    "name": "inspect-mesh",
    "description": "Inspects a mesh and returns a report with results",
    "version": "1",
    "start": "log",

    "parameterSchema": {
        "type": "object",
        "properties": {
            "meshFile": {
                "type": "string",
                "minLength": 1,
                "format": "file"
            },
            "inspectionTool": {
                "type": "string",
                "enum": [
                    "Meshlab",
                    "MeshSmith"
                ],
                "default": "Meshlab"
            },
            "pickupPath": {
                "type": "string",
                "minLength": 1
            },
            "deliveryPath": {
                "type": "string",
                "minLength": 1
            },
            "transportMethod": {
                "type": "string",
                "enum": [
                    "none",
                    "local"
                ],
                "default": "none"
            }
        },
        "required": [
            "meshFile"
        ],
        "additionalProperties": false
    },

    "steps": {
        "log": {
            "task": "Log",
            "pre": {
                "baseName": "$baseName(meshFile)",
                "delivery": {
                    "inspectionReport": "baseName & '-inspection.json'"
                }
            },
            "parameters": {
                "logToConsole": true,
                "logFile": "baseName & '-log.txt'",
                "reportFile": "baseName & '-report.json'"
            },
            "success": "'pickup'",
            "failure": "$failure"
        },
        "pickup": {
            "task": "Pickup",
            "description": "Get input files from client",
            "parameters": {
                "method": "transportMethod",
                "path": "$firstTrue(pickupPath, $currentDir)",
                "files": {
                    "meshFile": "meshFile"
                }
            },
            "success": "'inspect'",
            "failure": "$failure"
        },
        "inspect": {
            "task": "InspectMesh",
            "description": "Validate mesh and inspect topology",
            "parameters": {
                "meshFile": "meshFile",
                "reportFile": "delivery.inspectionReport",
                "tool": "inspectionTool"
            },
            "post": {
                "maxRayDistance": "$max($result.inspection.scene.geometry.size) * 0.01"
            },
            "success": "'delivery'",
            "failure": "$failure"
        },
        "delivery": {
            "task": "Delivery",
            "description": "Send result files back to client",
            "parameters": {
                "method": "transportMethod",
                "path": "$firstTrue(deliveryPath, pickupPath, $currentDir)",
                "files": "delivery"
            },
            "success": "$success",
            "failure": "$failure"
        }
    }
}

=== Smithsonian/dpo-cook/server/recipes/photogrammetry.json
{
    "id": "a0af238a-988f-4f3c-bedc-7db0b8220ed5",
    "name": "photogrammetry",
    "description": "Create mesh and texture from image set",
    "version": "1",
    "start": "log",

    "parameterSchema": {
        "type": "object",
        "properties": {
            "sourceImageFolder": {
                "type": "string",
                "minLength": 1,
                "format": "file"
            },
            "outputFileBaseName": {
                "type": "string",
                "minLength": 1
            },
            "tool": {
                "type": "string",
                "enum": [
                    "Metashape"
                ],
                "default": "Metashape"
            },
            "scalebarCSV": {
                "type": "string",
                "minLength": 1,
                "format": "file"
            },
            "generatePointCloud": {
                "type": "boolean",
                "default": false
            }
        },
        "required": [
            "sourceImageFolder"
        ],
        "advanced": [
            
        ],
        "additionalProperties": false
    },

    "steps": {
        "log": {
            "task": "Log",
            "description": "Enable logging services",
            "pre": {
                "outputFileBaseName": "$baseName($firstTrue(outputFileBaseName, sourceImageFolder))",
                "baseMeshName": "$firstTrue(outputFileBaseName, sourceImageFolder)"
            },
            "parameters": {
                "logToConsole": true,
                "reportFile": "outputFileBaseName & '-report.json'"
            },
            "success": "'pickup'",
            "failure": "$failure"
        },
        "pickup": {
            "task": "Pickup",
            "description": "Fetch input files from client",
            "parameters": {
                "method": "transportMethod",
                "path": "$firstTrue(pickupPath, $currentDir)",
                "files": {
                    "sourceImageFolder": "sourceImageFolder"
                }
            },
            "success": "'unzip'",
            "failure": "$failure"
        },
        "unzip": {
            "task": "Zip",
            "description": "Unzip image folder",
            "pre": {
                "deliverables": {
                    "objZipLow": "scaleToMeters ? baseMeshMapNameLow & '-obj_std.zip' : baseMeshMapNameLow & '-obj.zip'"
                }
            },
            "parameters": {
                "inputFile1": "sourceImageFolder",
                "operation": "'unzip'"
            },
            "success": "'photogrammetry'",
            "failure": "$failure"
        },
        "photogrammetry": {
            "task": "Photogrammetry",
            "description": "Create mesh and texture from image set.",
            "pre": {
                "deliverables": {
                    "meshFile": "baseMeshName & '-' & $lowercase(tool) & '.obj'",
                    "textureFile": "baseMeshName & '-texture-' & '.png'"
                }
            },
            "parameters": {
                "inputImageFolder": "sourceImageFolder",
                "outputFile": "deliverables.meshFile",
                "scalebarFile": "scalebarCSV",
                "generatePointCloud": "generatePointCloud",
                "tool": "tool",
                "timeout": 43200
            },
            "success": "'delivery'",
            "failure": "$failure"
        },
        "delivery": {
            "task": "Delivery",
            "description": "Send result files back to client",
            "parameters": {
                "method": "transportMethod",
                "path": "$firstTrue(deliveryPath, pickupPath, $currentDir)",
                "files": "deliverables"
            },
            "success": "$success",
            "failure": "$failure"
        }
    }
}

=== Smithsonian/dpo-cook/server/recipes/si-voyager-asset.json
{
    "id": "5490a618-4ebd-4763-a96a-abb9062c786b",
    "name": "si-voyager-asset",
    "description": "Generate Voyager package from single unmodified asset",
    "version": "5",
    "start": "pickup",

    "parameterSchema": {
        "type": "object",
        "properties": {
            "sourceMeshFile": {
                "type": "string",
                "minLength": 1,
                "format": "file"
            },
            "sourceDiffuseMapFile": {
                "type": "string",
                "minLength": 1,
                "format": "file"
            },
            "sourceOcclusionMapFile": {
                "type": "string",
                "minLength": 1,
                "format": "file"
            },
            "sourceEmissiveMapFile": {
                "type": "string",
                "minLength": 1,
                "format": "file"
            },
            "sourceMetallicRoughnessMapFile": {
                "type": "string",
                "minLength": 1,
                "format": "file"
            },
            "sourceNormalMapFile": {
                "type": "string",
                "minLength": 1,
                "format": "file"
            },
            "sourceZoneMapFile": {
                "type": "string",
                "minLength": 1,
                "format": "file"
            },
            "tool": {
                "type": "string",
                "enum": [
                    "MeshSmith",
                    "Blender"
                ],
                "default": "MeshSmith"
            },
            "svxFile": {
                "type": "string",
                "minLength": 1,
                "format": "file"
            },
            "metaDataFile": {
                "type": "string",
                "minLength": 1,
                "format": "file"
            },
            "outputFileBaseName": {
                "type": "string",
                "minLength": 1
            },
            "blendAlpha": {
                "type": "boolean",
                "default": false
            },
            "modelIndex": {
                "type": "integer",
                "minimum": 0,
                "default": 0
            },
            "assetQuality": {
                "type": "string",
                "minLength": 1,
                "default": "Thumb"
            },
            "units": {
                "type": "string",
                "enum": [ "mm", "cm", "m", "in", "ft", "yd" ],
                "default": "cm"
            },
            "alignCenter": {
                "type": "boolean",
                "default": false
            },
            "alignFloor": {
                "type": "boolean",
                "default": false
            },
            "tangentSpaceNormals": {
                "type": "boolean",
                "default": true
            },
            "generateGlb": {
                "type": "boolean",
                "default": true
            },
            "generateGltf": {
                "type": "boolean",
                "default": true
            },
            "useCompression": {
                "type": "boolean",
                "default": true
            }
        },
        "required": [
            "sourceMeshFile"
        ],
        "additionalProperties": false
    },

    "steps": {
        "pickup": {
            "task": "Pickup",
            "description": "Fetch input files from client",
            "pre": {
                "outputFileBaseName": "$baseName($firstTrue(outputFileBaseName, sourceMeshFile))"
            },
            "parameters": {
                "method": "transportMethod",
                "path": "$firstTrue(pickupPath, $currentDir)",
                "files": {
                    "meshFile": "sourceMeshFile",
                    "diffuseMapFile": "sourceDiffuseMapFile",
                    "occlusionMapFile": "sourceOcclusionMapFile",
                    "emissiveMapFile": "sourceEmissiveMapFile",
                    "metallicRoughnessMapFile": "sourceMetallicRoughnessMapFile",
                    "normalMapFile": "sourceNormalMapFile",
                    "zoneMapFile": "sourceZoneMapFile",
                    "documentFile": "svxFile",
                    "metaDataFile": "metaDataFile"
                }
            },
            "success": "'web-asset-glb'",
            "failure": "$failure"
        },
        "web-asset-glb": {
            "task": "WebAsset",
            "description": "Create binary, compressed, embedded glTF asset",
            "skip": "$not(generateGlb)",
            "pre": {
                "deliverables": {
                    "webAssetGlb": "outputFileBaseName & '-web.glb'"
                }
            },
            "parameters": {
                "outputFile": "deliverables.webAssetGlb",
                "meshFile": "sourceMeshFile",
                "diffuseMapFile": "sourceDiffuseMapFile",
                "occlusionMapFile": "sourceOcclusionMapFile",
                "emissiveMapFile": "sourceEmissiveMapFile",
                "metallicRoughnessMapFile": "sourceMetallicRoughnessMapFile",
                "normalMapFile": "sourceNormalMapFile",
                "zoneMapFile": "sourceZoneMapFile",
                "alignCenter": "alignCenter",
                "alignFloor": "alignFloor",
                "objectSpaceNormals": "$not(tangentSpaceNormals)",
                "useCompression": "useCompression",
                "compressionLevel": 10,
                "embedMaps": true,
                "writeBinary": true,
                "alphaBlend": "blendAlpha",
                "tool": "tool"
            },
            "success": "'web-asset-gltf'",
            "failure": "$failure"

        },
        "web-asset-gltf": {
            "task": "WebAsset",
            "description": "Create glTF asset",
            "skip": "$not(generateGltf)",
            "pre": {
                "deliverables": {
                    "webAssetGltf": "outputFileBaseName & '-web.gltf'",
                    "webAssetBin": "outputFileBaseName & '-web.bin'"
                }
            },
            "parameters": {
                "outputFile": "deliverables.webAssetGltf",
                "meshFile": "sourceMeshFile",
                "diffuseMapFile": "sourceDiffuseMapFile",
                "occlusionMapFile": "sourceOcclusionMapFile",
                "emissiveMapFile": "sourceEmissiveMapFile",
                "metallicRoughnessMapFile": "sourceMetallicRoughnessMapFile",
                "normalMapFile": "sourceNormalMapFile",
                "zoneMapFile": "sourceZoneMapFile",
                "alignCenter": "alignCenter",
                "alignFloor": "alignFloor",
                "objectSpaceNormals": "$not(tangentSpaceNormals)",
                "useCompression": false,
                "compressionLevel": 10,
                "embedMaps": false,
                "writeBinary": false,
                "alphaBlend": "blendAlpha",
                "tool": "tool"
            },
            "success": "'update-document'",
            "failure": "$failure"
        },
        "update-document": {
            "task": "Document",
            "description": "Add web model to document.json descriptor file",
            "pre": {
                "deliverables": {
                    "document": "$firstTrue(svxFile, 'scene.svx.json')"
                }
            },
            "parameters": {
                "documentFile": "deliverables.document",
                "metaDataFile": "metaDataFile",
                "modelIndex": "modelIndex",
                "modelName": "outputFileBaseName",
                "units": "units",
                "derivativeQuality": "assetQuality",
                "modelFile": "$firstTrue(deliverables.webAssetGlb, deliverables.webAssetGltf)",
                "numFaces": "numFaces",
                "mapSize": "mapSize"
            },
            "success": "'delivery'",
            "failure": "$failure"
        },
        "delivery": {
            "task": "Delivery",
            "description": "Send result files back to client",
            "parameters": {
                "method": "transportMethod",
                "path": "$firstTrue(deliveryPath, pickupPath, $currentDir)",
                "files": "deliverables"
            },
            "success": "$success",
            "failure": "$failure"
        }
    }
}

=== Smithsonian/dpo-cook/server/recipes/generate-sprite-sheet.json
{
    "id": "e4f7d37c-40a1-401a-8d9f-46d6ba733c1c",
    "name": "generate-sprite-sheet",
    "description": "Create sprite sheet from folder of files",
    "version": "1",
    "start": "log",

    "parameterSchema": {
        "type": "object",
        "properties": {
            "sourceFolderPath": {
                "type": "string",
                "minLength": 1
            },
            "filetype": {
                "type": "string",
                "minLength": 1
            },
            "outputFileBaseName": {
                "type": "string",
                "minLength": 1
            },
            "layoutX": {
                "type": "integer"
            },
            "layoutY": {
                "type": "integer"
            }
        },
        "required": [
            "sourceFolderPath"
        ],
        "additionalProperties": false
    },

    "steps": {
        "log": {
            "task": "Log",
            "description": "Enable logging services",
            "pre": {
                "outputFileBaseName": "$baseName($firstTrue(outputFileBaseName, sourceFolderPath))",
                "sourceFolderBaseName": "$baseName(sourceFolderPath)"
            },
            "parameters": {
                "logToConsole": true,
                "reportFile": "outputFileBaseName & '-report.json'"
            },
            "success": "'zip-files'",
            "failure": "$failure"
        },
        "zip-files": {
            "task": "Zip",
            "description": "Zip files direct from storage",
            "pre": {
                "deliverables": {
                    "fileZip": "sourceFolderBaseName & '.zip'"
                }
            },
            "parameters": {
                "inputFile1": "sourceFolderPath",
                "fileFilter": "filetype",
                "recursive": false,
                "outputFile": "deliverables.fileZip",
                "operation": "'path-zip'"
            },
            "success": "'unzip'",
            "failure": "$failure"
        },
        "unzip": {
            "task": "Zip",
            "description": "Unzip image folder",
            "parameters": {
                "inputFile1": "deliverables.fileZip",
                "operation": "'unzip'"
            },
            "success": "'create-sprite-map'",
            "failure": "$failure"
        },
        "create-sprite-map": {
            "task": "GenerateSpriteMap",
            "description": "Convert images to sprite sheet",
            "pre": {
                "deliverables": {
                    "spritesheet": "outputFileBaseName & '.jpg'"
                }
            },
            "parameters": {
                "inputImageFolder": "sourceFolderBaseName",
                "outputImageFile": "deliverables.spritesheet",
                "quality": "85",
                "resize": "300",
                "dimensionX": "layoutX",
                "dimensionY": "layoutY"
            },
            "success": "'delivery'",
            "failure": "$failure"
        },
        "delivery": {
            "task": "Delivery",
            "description": "Send result files back to client",
            "parameters": {
                "method": "transportMethod",
                "path": "$firstTrue(deliveryPath, pickupPath, $currentDir)",
                "files": "deliverables"
            },
            "success": "$success",
            "failure": "$failure"
        }
    }
}
