=== Smithsonian/dpo-cook/server/schemas/recipe.schema.json
{
    "$id": "https://schemas.3d.si.edu/cook/recipe.json",
    "$schema": "http://json-schema.org/draft-07/schema#",

    "title": "Smithsonian 3D Processing Recipe",

    "definitions": {
        "primitiveValue": {
            "$id": "#primitiveValue",
            "oneOf": [
                {
                    "type": "number"
                },
                {
                    "type": "boolean"
                },
                {
                    "type": "string"
                }
            ]
        },
        "taskParameter": {
            "$id": "#taskParameter",
            "oneOf": [
                {
                    "$ref": "#primitiveValue"
                },
                {
                    "type": "array",
                    "items": {
                        "$ref": "#primitiveValue"
                    }
                },
                {
                    "type": "object",
                    "items": {
                        "$ref": "#primitiveValue"
                    }

                }
            ]
        },
        "recipeParameterMetaSchema": {
            "$id": "#recipeParameterMetaSchema",
            "type": "object",
            "properties": {
                "type": {
                    "type": "string",
                    "const": "object"
                },
                "properties": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "object",
                        "oneOf": [
                            {
                                "properties": {
                                    "type": {
                                        "type": "string",
                                        "const": "number"
                                    },
                                    "minimum": {
                                        "type": "number"
                                    },
                                    "maximum": {
                                        "type": "number"
                                    },
                                    "multipleOf": {
                                        "type": "integer"
                                    },
                                    "default": {
                                        "type": "number"
                                    }
                                },
                                "required": [
                                    "type"
                                ]
                            },
                            {
                                "properties": {
                                    "type": {
                                        "type": "string",
                                        "const": "integer"
                                    },
                                    "minimum": {
                                        "type": "integer"
                                    },
                                    "maximum": {
                                        "type": "integer"
                                    },
                                    "multipleOf": {
                                        "type": "integer"
                                    },
                                    "default": {
                                        "type": "integer"
                                    }
                                },
                                "required": [
                                    "type"
                                ]
                            },
                            {
                                "properties": {
                                    "type": {
                                        "type": "string",
                                        "const": "boolean"
                                    },
                                    "default": {
                                        "type": "boolean"
                                    }
                                },
                                "required": [
                                    "type"
                                ]
                            },
                            {
                                "properties": {
                                    "type": {
                                        "type": "string",
                                        "const": "string"
                                    },
                                    "minLength": {
                                        "type": "integer"
                                    },
                                    "maxLength": {
                                        "type": "integer"
                                    },
                                    "default": {
                                        "type": "string"
                                    }
                                },
                                "required": [
                                    "type"
                                ]
                            }
                        ]
                    }
                },
                "required": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "additionalProperties": {
                    "type": "boolean",
                    "const": false
                }
            },
            "required": [
                "type",
                "properties",
                "additionalProperties"
            ]
        },
        "recipeStep": {
            "$id": "#recipeStep",
            "type": "object",
            "properties": {
                "task": {
                    "description": "name of the task to be executed in this step",
                    "type": "string",
                    "minLength": 1
                },
                "description": {
                    "description": "descriptive text for this recipe step",
                    "type": "string",
                    "minLength": 1
                },
                "parameters": {
                    "title": "task parameters",
                    "description": "primitive value or JSONata expression; strings must be put in quotes",
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#taskParameter"
                    }
                },
                "pre": {
                    "title": "variables defined before task is started",
                    "description": "primitive value or JSONata expression; strings must be put in quotes",
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#taskParameter"
                    }
                },
                "post": {
                    "title": "variables defined after task is done",
                    "description": "primitive value or JSONata expression; strings must be put in quotes",
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#taskParameter"
                    }
                },
                "success": {
                    "title": "name of next step to be executed in case of success",
                    "description": "name as string or JSONata expression; string must be put in quotes",
                    "type": "string",
                    "minLength": 1
                },
                "failure": {
                    "title": "name of next step to be executed in case of failure",
                    "description": "name as string or JSONata expression; string must be put in quotes",
                    "type": "string",
                    "minLength": 1
                }
            },
            "required": [
                "task",
                "parameters",
                "success",
                "failure"
            ],
            "additionalProperties": false
        }
    },

    "type": "object",
    "properties": {
        "id": {
            "description": "unique identifier for the recipe",
            "type": "string",
            "minLength": 1
        },
        "name": {
            "description": "recipe name",
            "type": "string",
            "minLength": 1
        },
        "description": {
            "description": "recipe description",
            "type": "string",
            "minLength": 1
        },
        "version": {
            "description": "version of the recipe, must be incremented each time recipe changes",
            "type": "string",
            "minLength": 1
        },
        "parameterSchema": {
            "description": "JSON schema for the recipe's parameters; the schema must be valid against this meta schema",
            "$ref": "#recipeParameterMetaSchema"
        },
        "start": {
            "description": "name of first step to be executed",
            "type": "string",
            "minLength": 1
        },
        "steps": {
            "description": "each recipe step consists of a task to be executed, and next steps in case of success or failure",
            "type": "object",
            "additionalProperties": {
                "$ref": "#recipeStep"
            }
        }
    },
    "required": [
        "id",
        "name",
        "version",
        "parameterSchema",
        "start",
        "steps"
    ],
    "additionalProperties": false
}

=== Smithsonian/dpo-cook/server/recipes-archive/si-ar-backfill-std.json
{
    "id": "ae568c31-4cca-402e-90ee-b0c802fe05cc",
    "name": "si-ar-backfill-fix",
    "description": "Generates AR derivatives and inserts into known good scene.",
    "version": "2",
    "start": "log",

    "parameterSchema": {
        "type": "object",
        "properties": {
            "sourceVoyagerARGlb": {
                "type": "string",
                "minLength": 1,
                "format": "file"
            },
            "sourceVoyagerARGlbSTD": {
                "type": "string",
                "minLength": 1,
                "format": "file"
            },
            "sourceUsdz": {
                "type": "string",
                "minLength": 1,
                "format": "file"
            },
            "svxFile": {
                "type": "string",
                "minLength": 1,
                "format": "file"
            },
            "outputFileBaseName": {
                "type": "string",
                "minLength": 1
            },
            "decimationTool": {
                "type": "string",
                "enum": [ "Meshlab", "RapidCompact" ],
                "default": "RapidCompact"
            },
            "preDecimatedUnwrappedARTargetFile": {
                "type": "string",
                "minLength": 1,
                "format": "file"
            },
            "bakeVertexColor": {
                "type": "boolean",
                "default": false
            },
            "diffuseMapQualityLowAR": {
                "type": "integer",
                "minimum": 0,
                "maximum": 100,
                "default": 79
            },
            "occlusionMapQualityLowAR": {
                "type": "integer",
                "minimum": 0,
                "maximum": 100,
                "default": 59
            },
            "normalMapQualityLowAR": {
                "type": "integer",
                "minimum": 0,
                "maximum": 100,
                "default": 89
            },
            "scaleToMeters": {
                "type": "boolean",
                "default": true
            },
            "numFacesAR": {
                "type": "integer",
                "minimum": 10000,
                "multipleOf": 1000,
                "default": 100000
            },
            "mapSizeAR": {
                "type": "integer",
                "minimum": 128,
                "maximum": 4096,
                "default": 2048
            },
            "inspectMesh": {
                "type": "boolean",
                "default": false
            },
            "remeshFaces": {
                "type": "integer",
                "default": 0
            },
            "cleanupMesh": {
                "type": "boolean",
                "default": false
            },
            "unwrapSegmentationStrengthLowAR": {
                "type": "number",
                "minimum": 0,
                "maximum": 1,
                "default": 0.7
            },
            "unwrapPackEffort": {
                "type": "number",
                "minimum": 0,
                "maximum": 1,
                "default": 0.7
            },
            "bakeTest": {
                "type": "boolean",
                "default": true
            },
            "maxRayDistance": {
                "type": "number",
                "default": 0
            },
            "occlusionRays": {
                "type": "integer",
                "minimum": 1,
                "maximum": 512,
                "default": 128
            }
        },
        "required": [
            "sourceVoyagerARGlb",
            "svxFile"
        ],
        "advanced": [
            "bakeTest", "inspectMesh", "unwrapPackEffort", "unwrapSegmentationStrengthLowAR", "remeshFaces",
            "cleanupMesh", "normalMapQualityLowAR", "occlusionMapQualityLowAR", "preDecimatedUnwrappedARTargetFile",
            "diffuseMapQualityLowAR", "occlusionRays", "maxRayDistance", "scaleToMeters",
            "numFacesAR", "mapSizeAR", "sourceMTLFile", "sourceDiffuseMapFile", "decimationTool"
        ],
        "additionalProperties": false
    },

    "steps": {
        "log": {
            "task": "Log",
            "description": "Enable logging services",
            "pre": {
            },
            "parameters": {
                "logToConsole": true,
                "reportFile": "'backfill-report.json'"
            },
            "success": "'pickup'",
            "failure": "$failure"
        },
        "pickup": {
            "task": "Pickup",
            "description": "Fetch input files from client",
            "pre": {
                
            },
            "parameters": {
                "method": "transportMethod",
                "path": "$firstTrue(pickupPath, $currentDir)",
                "files": {
                }
            },
            "success": "'update-document-ar1'",
            "failure": "$failure"
        },
        "update-document-ar1": {
            "task": "Document",
            "description": "Add voyager AR model to document.json descriptor file",
            "pre": {
                "deliverables": {
                    "scene_document": "$firstTrue(svxFile, 'scene.svx.json')"
                }
            },
            "parameters": {
                "documentFile": "deliverables.scene_document",
                "modelIndex": 0,
                "derivativeQuality": "'AR'",
                "modelFile": "sourceVoyagerARGlb",
                "numFaces": "numFacesAR",
                "mapSize": "mapSizeAR"
            },
            "success": "'update-document-ar2'",
            "failure": "$failure"
        },
        "update-document-ar2": {
            "task": "Document",
            "description": "Add Android AR model to document.json descriptor file",
            "pre": {
                "deliverables": {
                    "scene_document": "$firstTrue(svxFile, 'scene.svx.json')"
                }
            },
            "parameters": {
                "documentFile": "deliverables.scene_document",
                "modelIndex": 0,
                "derivativeUsage": "'App3D'",
                "derivativeQuality": "'AR'",
                "modelFile": "sourceVoyagerARGlbSTD",
                "numFaces": "numFacesAR",
                "mapSize": "mapSizeAR"
            },
            "success": "'update-document-ar3'",
            "failure": "$failure"
        },
        "update-document-ar3": {
            "task": "Document",
            "description": "Add usdz AR model to document.json descriptor file",
            "pre": {
                "deliverables": {
                    "scene_document": "$firstTrue(svxFile, 'scene.svx.json')"
                }
            },
            "parameters": {
                "documentFile": "deliverables.scene_document",
                "modelIndex": 0,
                "derivativeUsage": "'iOSApp3D'",
                "derivativeQuality": "'AR'",
                "modelFile": "sourceUsdz",
                "numFaces": "numFacesAR",
                "mapSize": "mapSizeAR"
            },
            "success": "'delivery'",
            "failure": "$failure"
        },
        "delivery": {
            "task": "Delivery",
            "description": "Send result files back to client",
            "parameters": {
                "method": "transportMethod",
                "path": "$firstTrue(deliveryPath, pickupPath, $currentDir)",
                "files": "deliverables"
            },
            "success": "$success",
            "failure": "$failure"
        }
    }
}

=== Smithsonian/dpo-cook/server/recipes/decimate-unwrap.json
{
    "id": "c92d4d0e-4404-4b9e-92ee-75a7e25e126a",
    "name": "decimate-unwrap",
    "description": "Decimate mesh and generate UV coordinates",
    "version": "1",
    "start": "pickup",

    "parameterSchema": {
        "type": "object",
        "properties": {
            "sourceMeshFile": {
                "type": "string",
                "minLength": 1,
                "format": "file"
            },
            "outputFileBaseName": {
                "type": "string",
                "minLength": 1
            },
            "numFaces": {
                "type": "integer",
                "minimum": 100,
                "default": 150000
            },
            "cleanupMesh": {
                "type": "boolean",
                "default": true
            },
            "inspectMesh": {
                "type": "boolean",
                "default": false
            }
        },
        "required": [
            "sourceMeshFile"
        ],
        "additionalProperties": false
    },

    "steps": {
        "pickup": {
            "task": "Pickup",
            "description": "Fetch input files from client",
            "pre": {
                "outputFileBaseName": "$baseName($firstTrue(outputFileBaseName, sourceMeshFile))",
                "baseMeshName": "$baseMeshName($firstTrue(outputFileBaseName, sourceMeshFile), numFaces)",
                "baseMeshMapName": "$baseMeshMapName($firstTrue(outputFileBaseName, sourceMeshFile), numFaces, mapSize)"
            },
            "parameters": {
                "method": "transportMethod",
                "path": "$firstTrue(pickupPath, $currentDir)",
                "files": {
                    "highPolyMeshFile": "sourceMeshFile"
                }
            },
            "success": "'decimate-meshlab'",
            "failure": "$failure"
        },
        "decimate-meshlab": {
            "task": "DecimateMesh",
            "description": "Decimate mesh using Meshlab",
            "pre": {
                "decimatedMeshFile": "baseMeshName & '-decimated-meshlab.obj'",
                "deliverables": {
                    "inspectionReport": "inspectMesh ? outputFileBaseName & '-inspection.json' : ''"
                }
            },
            "parameters": {
                "inputMeshFile": "sourceMeshFile",
                "outputMeshFile": "decimatedMeshFile",
                "numFaces": "numFaces",
                "cleanup": "cleanupMesh",
                "preserveTopology": true,
                "preserveBoundaries": true,
                "preserveTexCoords": false,
                "computeVertexNormals": "tangentSpaceNormals",
                "inspectMesh": "deliverables.inspectionReport"
            },
            "success": "'unwrap-rizom'",
            "failure": "'decimate-rapid'"
        },
        "unwrap-rizom": {
            "task": "UnwrapMesh",
            "description": "Unwrap mesh using RizomUV",
            "pre": {
                "deliverables": {
                    "unwrappedMeshObj": "baseMeshName & '-unwrapped.obj'",
                    "unwrappedMeshFbx": "baseMeshName & '-unwrapped.fbx'"
                }
            },
            "parameters": {
                "inputMeshFile": "decimatedMeshFile",
                "outputMeshFile": "deliverables.unwrappedMeshObj",
                "saveFbx": true,
                "saveObj": true,
                "mapSize": "mapSize",
                "segmentationStrength": "segmentationStrength",
                "packEffort": "packEffort"
            },
            "success": "'delivery'",
            "failure": "$failure"
        },
        "delivery": {
            "task": "Delivery",
            "description": "Send result files back to client",
            "parameters": {
                "method": "transportMethod",
                "path": "$firstTrue(deliveryPath, pickupPath, $currentDir)",
                "files": "deliverables"
            },
            "success": "$success",
            "failure": "$failure"
        }
    }
}

=== Smithsonian/dpo-cook/server/recipes/rc-to-hd.json
{
    "id": "e06ade8e-b36a-4aa2-9145-6616ede1e5fa",
    "name": "rc-to-hd",
    "description": "[DRAFT!] Converts RC output files to HD web assets",
    "version": "1",
    "start": "log",

    "parameterSchema": {
        "type": "object",
        "properties": {
            "someFile": {
                "type": "string",
                "minLength": 1,
                "format": "file"
            },
            "pickupPath": {
                "type": "string",
                "minLength": 1
            },
            "deliveryPath": {
                "type": "string",
                "minLength": 1
            },
            "transportMethod": {
                "type": "string",
                "enum": [
                    "none",
                    "local"
                ],
                "default": "none"
            }
        },
        "required": [
            "someFile"
        ],
        "additionalProperties": false
    },

    "steps": {
        "log": {
            "task": "Log",
            "description": "Enable logging services",
            "parameters": {
                "logToConsole": true,
                "reportFile": "$baseName(someFile) & '-report.json'"
            },
            "success": "'pickup'",
            "failure": "$failure"
        },
        "pickup": {
            "task": "Pickup",
            "description": "Fetch input files from client",
            "parameters": {
                "method": "transportMethod",
                "path": "$firstTrue(pickupPath, $currentDir)",
                "files": {
                    "someFile": "someFile"
                }
            },
            "success": "'process'",
            "failure": "$failure"
        },
        "process": {
            "task": "Dummy",
            "description": "Dummy Task",
            "pre": {
            },
            "parameters": {
                "outcome": "success",
                "duration": 1
            },
            "post": {
            },
            "success": "'delivery'",
            "failure": "$failure"
        },
        "delivery": {
            "task": "Delivery",
            "description": "Send result files back to client",
            "pre": {
                "deliverables": {
                    "someFile": "someFile"
                }
            },
            "parameters": {
                "method": "transportMethod",
                "path": "$firstTrue(deliveryPath, pickupPath, $currentDir)",
                "files": "deliverables"
            },
            "success": "$success",
            "failure": "$failure"
        }
    }
}

=== Smithsonian/dpo-cook/server/recipes-archive/migrate-play.json
{
    "id": "8a2e8556-3c39-48a2-b432-591f480b7d69",
    "name": "migrate-play",
    "description": "Converts a Play Box to a Voyager Scene Document",
    "version": "3",
    "start": "log",

    "parameterSchema": {
        "type": "object",
        "properties": {
            "boxId": {
                "type": "integer"
            },
            "annotationStyle": {
                "type": "string",
                "enum": [ "Standard", "Extended", "Circle" ],
                "default": "Circle"
            },
            "migrateAnnotationColor": {
                "type": "boolean",
                "default": false
            },
            "createReadingSteps": {
                "type": "boolean",
                "default": false
            },
            "edanEntry": {
                "type": "string"
            },
            "drupalBaseUrl": {
                "type": "string",
                "default": "https://3d.si.edu"
            },
            "payloadBaseUrl": {
                "type": "string",
                "default": "https://3d.si.edu/sites/default/files/box_payloads"
            },
            "cdnBaseUrl": {
                "type": "string",
                "default": "https://d39fxlie76wg71.cloudfront.net"
            }
        },
        "required": [
            "boxId"
        ],
        "additionalProperties": false
    },

    "steps": {
        "log": {
            "task": "Log",
            "pre": {
                "baseName": "baseName ? baseName & '-' : ''"
            },
            "parameters": {
                "logToConsole": true,
                "logFile": "baseName & 'log.txt'",
                "reportFile": "baseName & 'report.json'"
            },
            "success": "'migrate'",
            "failure": "$failure"
        },
        "migrate": {
            "task": "MigratePlay",
            "pre": {
                "deliverables": {
                }
            },
            "parameters": {
                "boxId": "boxId",
                "annotationStyle": "annotationStyle",
                "migrateAnnotationColor": "migrateAnnotationColor",
                "createReadingSteps": "createReadingSteps",
                "edanEntry": "edanEntry",
                "drupalBaseUrl": "drupalBaseUrl",
                "payloadBaseUrl": "payloadBaseUrl",
                "cdnBaseUrl": "cdnBaseUrl"
            },
            "post": {
                "deliverables": "$result.files"
            },
            "success": "'delivery'",
            "failure": "$failure"
        },
        "delivery": {
            "task": "Delivery",
            "description": "Send result files back to client",
            "parameters": {
                "method": "none",
                "path": "$currentDir",
                "files": "deliverables"
            },
            "success": "$success",
            "failure": "$failure"
        }
    }
}

=== Smithsonian/dpo-cook/server/recipes/clean.json
{
    "id": "08ac51c5-5fef-47a1-b04b-b02577d6418c",
    "name": "clean",
    "description": "Clean mesh of common issues",
    "version": "1",
    "start": "pickup",

    "parameterSchema": {
        "type": "object",
        "properties": {
            "sourceMeshFile": {
                "type": "string",
                "minLength": 1,
                "format": "file"
            },
            "outputFileBaseName": {
                "type": "string",
                "minLength": 1
            },
            "sourceDiffuseMapFile": {
                "type": "string",
                "minLength": 1,
                "format": "file"
            },
            "sourceMTLFile": {
                "type": "string",
                "minLength": 1,
                "format": "file"
            }
        },
        "required": [
            "sourceMeshFile"
        ],
        "advanced": [
            
        ],
        "additionalProperties": false
    },

    "steps": {
        "pickup": {
            "task": "Pickup",
            "description": "Fetch input files from client",
            "pre": {
                "baseMeshName": "$baseName($firstTrue(outputFileBaseName, sourceMeshFile))"
            },
            "parameters": {
                "method": "transportMethod",
                "path": "$firstTrue(pickupPath, $currentDir)",
                "files": {
                    "highPolyMeshFile": "sourceMeshFile"
                }
            },
            "success": "'clean-mesh'",
            "failure": "$failure"
        },
        "clean-mesh": {
            "task": "CleanupMesh",
            "description": "Clean up mesh",
            "pre": {
                "deliverables": {
                    "cleanedMeshFile": "baseMeshName & '-cleaned' & '.obj'"
                }
            },
            "parameters": {
                "inputMeshFile": "sourceMeshFile",
                "outputMeshFile": "deliverables.cleanedMeshFile",
                "timeout": 1200
            },
            "success": "'delivery'",
            "failure": "$failure"
        },
        "delivery": {
            "task": "Delivery",
            "description": "Send result files back to client",
            "parameters": {
                "method": "transportMethod",
                "path": "$firstTrue(deliveryPath, pickupPath, $currentDir)",
                "files": "deliverables"
            },
            "success": "$success",
            "failure": "$failure"
        }
    }
}
