=== Smithsonian/dpo-cook/server/schemas/recipe.schema.json
{
    "$id": "https://schemas.3d.si.edu/cook/recipe.json",
    "$schema": "http://json-schema.org/draft-07/schema#",

    "title": "Smithsonian 3D Processing Recipe",

    "definitions": {
        "primitiveValue": {
            "$id": "#primitiveValue",
            "oneOf": [
                {
                    "type": "number"
                },
                {
                    "type": "boolean"
                },
                {
                    "type": "string"
                }
            ]
        },
        "taskParameter": {
            "$id": "#taskParameter",
            "oneOf": [
                {
                    "$ref": "#primitiveValue"
                },
                {
                    "type": "array",
                    "items": {
                        "$ref": "#primitiveValue"
                    }
                },
                {
                    "type": "object",
                    "items": {
                        "$ref": "#primitiveValue"
                    }

                }
            ]
        },
        "recipeParameterMetaSchema": {
            "$id": "#recipeParameterMetaSchema",
            "type": "object",
            "properties": {
                "type": {
                    "type": "string",
                    "const": "object"
                },
                "properties": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "object",
                        "oneOf": [
                            {
                                "properties": {
                                    "type": {
                                        "type": "string",
                                        "const": "number"
                                    },
                                    "minimum": {
                                        "type": "number"
                                    },
                                    "maximum": {
                                        "type": "number"
                                    },
                                    "multipleOf": {
                                        "type": "integer"
                                    },
                                    "default": {
                                        "type": "number"
                                    }
                                },
                                "required": [
                                    "type"
                                ]
                            },
                            {
                                "properties": {
                                    "type": {
                                        "type": "string",
                                        "const": "integer"
                                    },
                                    "minimum": {
                                        "type": "integer"
                                    },
                                    "maximum": {
                                        "type": "integer"
                                    },
                                    "multipleOf": {
                                        "type": "integer"
                                    },
                                    "default": {
                                        "type": "integer"
                                    }
                                },
                                "required": [
                                    "type"
                                ]
                            },
                            {
                                "properties": {
                                    "type": {
                                        "type": "string",
                                        "const": "boolean"
                                    },
                                    "default": {
                                        "type": "boolean"
                                    }
                                },
                                "required": [
                                    "type"
                                ]
                            },
                            {
                                "properties": {
                                    "type": {
                                        "type": "string",
                                        "const": "string"
                                    },
                                    "minLength": {
                                        "type": "integer"
                                    },
                                    "maxLength": {
                                        "type": "integer"
                                    },
                                    "default": {
                                        "type": "string"
                                    }
                                },
                                "required": [
                                    "type"
                                ]
                            }
                        ]
                    }
                },
                "required": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "additionalProperties": {
                    "type": "boolean",
                    "const": false
                }
            },
            "required": [
                "type",
                "properties",
                "additionalProperties"
            ]
        },
        "recipeStep": {
            "$id": "#recipeStep",
            "type": "object",
            "properties": {
                "task": {
                    "description": "name of the task to be executed in this step",
                    "type": "string",
                    "minLength": 1
                },
                "description": {
                    "description": "descriptive text for this recipe step",
                    "type": "string",
                    "minLength": 1
                },
                "parameters": {
                    "title": "task parameters",
                    "description": "primitive value or JSONata expression; strings must be put in quotes",
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#taskParameter"
                    }
                },
                "pre": {
                    "title": "variables defined before task is started",
                    "description": "primitive value or JSONata expression; strings must be put in quotes",
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#taskParameter"
                    }
                },
                "post": {
                    "title": "variables defined after task is done",
                    "description": "primitive value or JSONata expression; strings must be put in quotes",
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#taskParameter"
                    }
                },
                "success": {
                    "title": "name of next step to be executed in case of success",
                    "description": "name as string or JSONata expression; string must be put in quotes",
                    "type": "string",
                    "minLength": 1
                },
                "failure": {
                    "title": "name of next step to be executed in case of failure",
                    "description": "name as string or JSONata expression; string must be put in quotes",
                    "type": "string",
                    "minLength": 1
                }
            },
            "required": [
                "task",
                "parameters",
                "success",
                "failure"
            ],
            "additionalProperties": false
        }
    },

    "type": "object",
    "properties": {
        "id": {
            "description": "unique identifier for the recipe",
            "type": "string",
            "minLength": 1
        },
        "name": {
            "description": "recipe name",
            "type": "string",
            "minLength": 1
        },
        "description": {
            "description": "recipe description",
            "type": "string",
            "minLength": 1
        },
        "version": {
            "description": "version of the recipe, must be incremented each time recipe changes",
            "type": "string",
            "minLength": 1
        },
        "parameterSchema": {
            "description": "JSON schema for the recipe's parameters; the schema must be valid against this meta schema",
            "$ref": "#recipeParameterMetaSchema"
        },
        "start": {
            "description": "name of first step to be executed",
            "type": "string",
            "minLength": 1
        },
        "steps": {
            "description": "each recipe step consists of a task to be executed, and next steps in case of success or failure",
            "type": "object",
            "additionalProperties": {
                "$ref": "#recipeStep"
            }
        }
    },
    "required": [
        "id",
        "name",
        "version",
        "parameterSchema",
        "start",
        "steps"
    ],
    "additionalProperties": false
}

=== Smithsonian/dpo-cook/server/recipes/transform.json
{
    "id": "c55feac5-5e12-4d61-ac34-a62aa2f378ac",
    "name": "transform",
    "description": "Converts and transforms a mesh",
    "version": "1",
    "start": "pickup",

    "parameterSchema": {
        "type": "object",
        "properties": {
            "inputMeshFile": {
                "type": "string",
                "minLength": 1,
                "format": "file"
            },
            "outputMeshFile": {
                "type": "string",
                "minLength": 1
            },
            "baseName": {
                "type": "string",
                "minLength": 1
            },
            "swizzle": {
                "type": "string",
                "minLength": 6,
                "maxLength": 6
            },
            "alignX": {
                "type": "string",
                "enum": [ "start", "end", "center" ]
            },
            "alignY": {
                "type": "string",
                "enum": [ "start", "end", "center" ]
            },
            "alignZ": {
                "type": "string",
                "enum": [ "start", "end", "center" ]
            },
            "translateX": {
                "type": "number"
            },
            "translateY": {
                "type": "number"
            },
            "translateZ": {
                "type": "number"
            },
            "scale": {
                "type": "number"
            },
            "joinVertices": {
                "type": "boolean",
                "default": false
            },
            "stripNormals": {
                "type": "boolean",
                "default": false
            },
            "stripTexCoords": {
                "type": "boolean",
                "default": false
            }
        },
        "required": [
            "inputMeshFile"
        ],
        "additionalProperties": false
    },

    "steps": {
        "pickup": {
            "task": "Pickup",
            "description": "Fetch input files from client",
            "pre": {
                "baseName": "$baseName($firstTrue(baseName, inputMeshFile))"
            },
            "parameters": {
                "method": "transportMethod",
                "path": "$firstTrue(pickupPath, $currentDir)",
                "files": {
                    "inputMeshFile": "inputMeshFile"
                }
            },
            "success": "'transform'",
            "failure": "$failure"
        },
        "transform": {
            "task": "ConvertMesh",
            "description": "Convert and transform mesh",
            "pre": {
                "deliverables": {
                    "transformedMeshFile": "$firstTrue(outputMeshFile, baseName & ',-transformed.obj')"
                }
            },
            "parameters": {
                "inputMeshFile": "inputMeshFile",
                "outputMeshFile": "deliverables.transformedMeshFile",
                "swizzle": "swizzle",
                "alignX": "alignX",
                "alignY": "alignY",
                "alignZ": "alignZ",
                "translateX": "translateX",
                "translateY": "translateY",
                "translateZ": "translateZ",
                "scale": "scale",
                "joinVertices": "joinVertices",
                "stripNormals": "stripNormals",
                "stripTexCoords": "stripTexCoords"
            },
            "success": "'delivery'",
            "failure": "$failure"
        },
        "delivery": {
            "task": "Delivery",
            "description": "Send result files back to client",
            "parameters": {
                "method": "transportMethod",
                "path": "$firstTrue(deliveryPath, pickupPath, $currentDir)",
                "files": "deliverables"
            },
            "success": "$success",
            "failure": "$failure"
        }
    }
}

=== Smithsonian/dpo-cook/server/recipes/web-usdz.json
{
    "id": "a12161bb-265f-4979-80db-65f739dcc156",
    "name": "web-usdz",
    "description": "Create usdz web asset",
    "version": "1",
    "start": "pickup",

    "parameterSchema": {
        "type": "object",
        "properties": {
            "meshFile": {
                "type": "string",
                "minLength": 1,
                "format": "file"
            },
            "diffuseMapFile": {
                "type": "string",
                "minLength": 1,
                "format": "file"
            },
            "mtlFile": {
                "type": "string",
                "minLength": 1,
                "format": "file"
            },
            "baseName": {
                "type": "string",
                "minLength": 1
            },
            "tool": {
                "type": "string",
                "enum": [
                    "Unity",
                    "RapidCompact"
                ],
                "default": "Unity"
            }
        },
        "required": [
            "meshFile"
        ],
        "additionalProperties": false
    },

    "steps": {
        "pickup": {
            "task": "Pickup",
            "description": "Fetch input files from client",
            "pre": {
                "baseName": "$baseName($firstTrue(baseName, meshFile))"
            },
            "parameters": {
                "method": "transportMethod",
                "path": "$firstTrue(pickupPath, $currentDir)",
                "files": {
                    "meshFile": "meshFile",
                    "diffuseMapFile": "diffuseMapFile",
                    "occlusionMapFile": "occlusionMapFile"
                }
            },
            "success": "'web-asset-usdz'",
            "failure": "$failure"
        },
        "web-asset-usdz": {
            "task": "GenerateUsdz",
            "description": "Create usdz asset",
            "skip": "$not(generateBinary)",
            "pre": {
                "deliverables": {
                    "webAssetUsdz": "baseName & '.usdz'"
                }
            },
            "parameters": {
                "outputFile": "deliverables.webAssetUsdz",
                "objFile": "meshFile",
                "textureFile": "diffuseMapFile",
                "mtlFile": "mtlFile",
                "tool": "tool"
            },
            "success": "'delivery'",
            "failure": "$failure"

        },
        "delivery": {
            "task": "Delivery",
            "description": "Send result files back to client",
            "parameters": {
                "method": "transportMethod",
                "path": "$firstTrue(deliveryPath, pickupPath, $currentDir)",
                "files": "deliverables"
            },
            "success": "$success",
            "failure": "$failure"
        }
    }
}

=== Smithsonian/dpo-cook/server/recipes/process-raw.json
{
    "id": "466c3283-0b15-4312-901b-6e307fd6be44",
    "name": "process-raw",
    "description": "Process raw images for photogrammetry workflow",
    "version": "1",
    "start": "log",

    "parameterSchema": {
        "type": "object",
        "properties": {
            "sourceImageFolder": {
                "type": "string",
                "minLength": 1,
                "format": "file"
            },
            "outputFileBaseName": {
                "type": "string",
                "minLength": 1
            },
            "tool": {
                "type": "string",
                "enum": [
                    "RawTherapee"
                ],
                "default": "RawTherapee"
            }
        },
        "required": [
            "sourceImageFolder"
        ],
        "advanced": [
            
        ],
        "additionalProperties": false
    },

    "steps": {
        "log": {
            "task": "Log",
            "description": "Enable logging services",
            "pre": {
                "outputFileBaseName": "$baseName($firstTrue(outputFileBaseName, sourceImageFolder))"
            },
            "parameters": {
                "logToConsole": true,
                "reportFile": "outputFileBaseName & '-report.json'"
            },
            "success": "'pickup'",
            "failure": "$failure"
        },
        "pickup": {
            "task": "Pickup",
            "description": "Fetch input files from client",
            "parameters": {
                "method": "transportMethod",
                "path": "$firstTrue(pickupPath, $currentDir)",
                "files": {
                    "sourceImageFolder": "sourceImageFolder"
                }
            },
            "success": "'unzip'",
            "failure": "$failure"
        },
        "unzip": {
            "task": "Zip",
            "description": "Unzip image folder",
            "parameters": {
                "inputFile1": "sourceImageFolder",
                "operation": "'unzip'"
            },
            "success": "'make-dir'",
            "failure": "$failure"
        },
        "make-dir": {
            "task": "FileOperation",
            "description": "Make output folder",
            "parameters": {
                "name": "outputFileBaseName & '_processed'",
                "operation": "'CreateFolder'"
            },
            "success": "'process-raw'",
            "failure": "$failure"
        },
        "process-raw": {
            "task": "ProcessRaw",
            "description": "Convert raw images to jpg and process for photogrammetry pipeline.",
            "pre": {
                "deliverables": {
                    "meshFile": "baseMeshName & '-' & $lowercase(tool) & '.obj'"
                }
            },
            "parameters": {
                "inputImageFolder": "sourceImageFolder",
                
                "tool": "tool",
                "timeout": 4300
            },
            "success": "'delivery'",
            "failure": "$failure"
        },
        "delivery": {
            "task": "Delivery",
            "description": "Send result files back to client",
            "parameters": {
                "method": "transportMethod",
                "path": "$firstTrue(deliveryPath, pickupPath, $currentDir)",
                "files": "deliverables"
            },
            "success": "$success",
            "failure": "$failure"
        }
    }
}

=== Smithsonian/dpo-cook/server/recipes/merge-img-channels.json
{
    "id": "4deeb2c6-db7a-4d15-a8d8-e58532fbf5fd",
    "name": "merge-img-channels",
    "description": "Merges channels of multiple input images into one.",
    "version": "1",
    "start": "log",

    "parameterSchema": {
        "type": "object",
        "properties": {
            "redChannelMapFile": {
                "type": "string",
                "minLength": 1,
                "format": "file"
            },
            "greenChannelMapFile": {
                "type": "string",
                "minLength": 1,
                "format": "file"
            },
            "blueChannelMapFile": {
                "type": "string",
                "minLength": 1,
                "format": "file"
            },
            "alphaChannelMapFile": {
                "type": "string",
                "minLength": 1,
                "format": "file"
            },
            "outputFileBaseName": {
                "type": "string",
                "minLength": 1
            }
        },
        "required": [
            "redChannelMapFile" ,"greenChannelMapFile", "blueChannelMapFile"
        ],
        "advanced": [
            
        ],
        "additionalProperties": false
    },

    "steps": {
        "log": {
            "task": "Log",
            "description": "Enable logging services",
            "pre": {
                "outputFileBaseName": "$firstTrue(outputFileBaseName, 'combined_map')"
            },
            "parameters": {
                "logToConsole": true,
                "reportFile": "outputFileBaseName & '-report.json'"
            },
            "success": "'merge-channels'",
            "failure": "$failure"
        },
        "merge-channels": {
            "task": "MergeImageChannels",
            "description": "Merge image channels",
            "pre": {
                "deliverables": {
                    "outputFile": "alphaChannelMapFile ? outputFileBaseName & '.png' : outputFileBaseName & '.jpg'"
                }
            },
            "parameters": {
                "redChannelMapFile": "redChannelMapFile",
                "greenChannelMapFile": "greenChannelMapFile",
                "blueChannelMapFile": "blueChannelMapFile",
                "alphaChannelMapFile": "alphaChannelMapFile",
                "outputMapFile": "deliverables.outputFile",
                "timeout": 600
            },
            "success": "'delivery'",
            "failure": "$failure"
        },
        "delivery": {
            "task": "Delivery",
            "description": "Send result files back to client",
            "parameters": {
                "method": "transportMethod",
                "path": "$firstTrue(deliveryPath, pickupPath, $currentDir)",
                "files": "deliverables"
            },
            "success": "$success",
            "failure": "$failure"
        }
    }
}

=== Smithsonian/dpo-cook/server/recipes/bake.json
{
    "id": "2fe782ca-93c4-4269-a06a-c764ad87558b",
    "name": "bake",
    "description": "Bake diffuse, occlusion, normal maps",
    "version": "1",
    "start": "pickup",

    "parameterSchema": {
        "type": "object",
        "properties": {
            "highPolyMeshFile": {
                "type": "string",
                "minLength": 1,
                "format": "file"
            },
            "highPolyDiffuseMapFile": {
                "type": "string",
                "minLength": 1,
                "format": "file"
            },
            "lowPolyUnwrappedMeshFile": {
                "type": "string",
                "minLength": 1,
                "format": "file"
            },
            "numFaces": {
                "type": "integer",
                "minimum": 10000,
                "multipleOf": 1000,
                "default": 250000
            },
            "mapSize": {
                "type": "integer",
                "minimum": 128,
                "maximum": 8192,
                "default": 4096
            },
            "bakeOcclusion": {
                "type": "boolean",
                "default": true
            },
            "bakeNormals": {
                "type": "boolean",
                "default": true
            },
            "bakeTest": {
                "type": "boolean",
                "default": false
            },
            "maxRayDistance": {
                "type": "number",
                "default": 0
            },
            "occlusionRays": {
                "type": "integer",
                "minimum": 1,
                "maximum": 512,
                "default": 128
            },
            "tangentSpaceNormals": {
                "type": "boolean",
                "default": true
            }
        },
        "required": [
            "highPolyMeshFile",
            "lowPolyUnwrappedMeshFile"
        ],
        "additionalProperties": false
    },

    "steps": {
        "pickup": {
            "task": "Pickup",
            "description": "Fetch input files from client",
            "pre": {
                "baseName": "$baseName(highPolyMeshFile)",
                "baseMeshName": "$baseMeshName(highPolyMeshFile, numFaces)",
                "baseMeshMapName": "$baseMeshMapName(highPolyMeshFile, numFaces, mapSize)",
                "bakeDiffuse": "$exists(highPolyDiffuseMapFile)"
            },
            "parameters": {
                "method": "transportMethod",
                "path": "$firstTrue(pickupPath, $currentDir)",
                "files": {
                    "highPolyMeshFile": "highPolyMeshFile",
                    "lowPolyUnwrappedMeshFile": "lowPolyUnwrappedMeshFile",
                    "highPolyDiffuseMapFile": "highPolyDiffuseMapFile"
                }
            },
            "success": "'inspect-unwrapped'",
            "failure": "$failure"
        },
        "inspect-unwrapped": {
            "task": "InspectMesh",
            "description": "Calculate mesh size and max. ray distance for bake",
            "skip": "maxRayDistance > 0",
            "parameters": {
                "meshFile": "lowPolyUnwrappedMeshFile",
                "tool": "'MeshSmith'"
            },
            "post": {
                "autoRayDistance": "$min($result.inspection.scene.geometry.size) * 0.01"
            },
            "success": "'bake'",
            "failure": "$failure"
        },
        "bake": {
            "task": "BakeMaps",
            "description": "Bake diffuse, normal and occlusion maps using xNormal",
            "pre": {
                "mapBaseName": "baseMeshMapName & '.png'"
            },
            "parameters": {
                "highPolyMeshFile": "highPolyMeshFile",
                "highPolyDiffuseMapFile": "highPolyDiffuseMapFile",
                "lowPolyUnwrappedMeshFile": "lowPolyUnwrappedMeshFile",
                "mapBaseName": "mapBaseName",
                "mapSize": "mapSize",
                "maxRayDistance": "maxRayDistance > 0 ? maxRayDistance : autoRayDistance",
                "bakeDiffuse": "bakeDiffuse",
                "bakeOcclusion": "bakeOcclusion",
                "bakeNormals": "bakeNormals",
                "bakeTest": "bakeTest",
                "occlusionRays": "occlusionRays",
                "tangentSpaceNormals": "tangentSpaceNormals",
                "timeout": 1200
            },
            "post": {
                "deliverables": {
                    "diffuseMapMaster": "bakeDiffuse ? (baseMeshMapName & '-diffuse.png') : ''",
                    "occlusionMapMaster": "bakeOcclusion ? (baseMeshMapName & '-occlusion.png') : ''",
                    "normalMapMaster": "bakeNormals ? (baseMeshMapName & '-normals.png') : ''",
                    "testMap": "bakeTest ? (baseMeshMapName & '-test.png') : ''"
                }
            },
            "success": "'convert-occlusion-map'",
            "failure": "$failure"
        },
        "delivery": {
            "task": "Delivery",
            "description": "Send result files back to client",
            "parameters": {
                "method": "transportMethod",
                "path": "$firstTrue(deliveryPath, pickupPath, $currentDir)",
                "files": "deliverables"
            },
            "success": "$success",
            "failure": "$failure"
        }
    }
}
